"""
data/parametric_examples.py
============================
Deterministic parametric expansion of DPO training triples.

No API calls. Each scenario type is hand-written; examples are generated by
substituting parameter combinations. Guarantees:
  - Domain balance: ~830 examples per domain across 6 domains
  - 100% pass rate on verify_triple (explicit qualifier words in faithful_summary)
  - No template collapse: each scenario type has varied system names, values, contexts
  - Qualifier diversity: 6 different qualifier phrases per template
"""

from __future__ import annotations
import itertools
import random
import uuid
from typing import Any

# ---------------------------------------------------------------------------
# Qualifier phrase pools — all appear in _FAITHFULNESS_MARKERS_LOWER
# ---------------------------------------------------------------------------
_QUAL_EXPLICIT = [
    "unverified", "unconfirmed", "not confirmed", "not yet confirmed",
    "approximately", "roughly", "probably", "maybe", "might be",
    "preliminary", "assumed", "reportedly", "estimate",
    "haven't confirmed", "I believe", "I think", "uncertain",
    "not validated", "subject to change", "pending verification",
    "awaiting confirmation",
]

_GHOST_QUAL = [
    "unverified", "unconfirmed", "not confirmed", "not validated",
    "assumed", "reportedly", "subject to change", "awaiting confirmation",
]


# ---------------------------------------------------------------------------
# Helper: expand a template dict into TripleExample-ready dicts
# ---------------------------------------------------------------------------

def _expand(
    template: dict[str, Any],
    qualifier_pool: list[str] | None = None,
) -> list[dict]:
    """
    Expand a scenario template into a list of example dicts.

    template keys:
      domain, qualifier_type, is_ghost,
      conv_template:       str with {param_*} + optional {qualifier}
      faithful_template:   str with {param_*} + {qualifier}
      unfaithful_template: str with {param_*}  (NO qualifier)
      variants:            list of dicts — each a full parameter set
    """
    pool = qualifier_pool if qualifier_pool else (
        _GHOST_QUAL if template.get("is_ghost") else _QUAL_EXPLICIT
    )
    examples = []
    for variant in template["variants"]:
        for qual in pool[:6]:  # max 6 qualifier phrases per variant
            v = dict(variant)
            v["qualifier"] = qual
            try:
                conv = template["conv_template"].format(**v)
                faithful = template["faithful_template"].format(**v)
                unfaithful = template["unfaithful_template"].format(**v)
            except KeyError:
                continue
            # Sanity: unfaithful must not contain qualifier words
            u_lo = unfaithful.lower()
            if any(q in u_lo for q in pool):
                continue
            # Sanity: faithful must contain qualifier
            if qual.lower() not in faithful.lower():
                continue
            examples.append({
                "id": str(uuid.uuid4()),
                "input_conversation": conv.strip(),
                "faithful_summary": faithful.strip(),
                "unfaithful_summary": unfaithful.strip(),
                "source_scenario_id": template["scenario_id"],
                "qualifier_type": template["qualifier_type"],
                "domain": template["domain"],
                "is_ghost": template["is_ghost"],
            })
    return examples


# ===========================================================================
# DOMAIN: api
# ===========================================================================

_API_TEMPLATES = [

    {
        "scenario_id": "api_rate_limit_hedged",
        "domain": "api", "qualifier_type": "vendor_claim", "is_ghost": False,
        "conv_template": (
            "User: I looked at the {system} docs — I think the rate limit is around {limit} "
            "requests per minute on the standard plan, but I'm not 100% sure.\n"
            "Assistant: Got it, that will affect how we batch our calls.\n"
            "User: We need to implement backoff to handle 429 responses.\n"
            "Assistant: I'll add exponential backoff capped at {retries} retries with jitter "
            "to avoid thundering herd on the {system} endpoint."
        ),
        "faithful_template": (
            "User believes {system}'s rate limit is {qualifier} {limit} req/min on the "
            "standard plan — should be verified from current documentation before shipping. "
            "Exponential backoff with {retries} retries will handle 429 responses."
        ),
        "unfaithful_template": (
            "{system}'s standard plan rate limit is {limit} requests per minute. "
            "Exponential backoff with {retries} retries will be implemented for 429 responses."
        ),
        "variants": [
            {"system": s, "limit": l, "retries": r}
            for s in ["Stripe", "Twilio", "SendGrid", "Mailgun", "Postmark", "Plaid"]
            for l in [50, 100, 200, 500, 1000]
            for r in [3, 5]
        ],
    },

    {
        "scenario_id": "api_rate_limit_ghost",
        "domain": "api", "qualifier_type": "vendor_claim", "is_ghost": True,
        "conv_template": (
            "User: The {system} API rate limit is {limit} requests per minute.\n"
            "Assistant: That constrains our parallel processing design.\n"
            "User: We're currently making about {current} requests per minute during peak.\n"
            "Assistant: We're close to the ceiling. I'll add rate tracking and alert at "
            "{alert}% utilization to catch spikes before we hit 429s."
        ),
        "faithful_template": (
            "{system} API rate limit is stated as {limit} req/min — {qualifier} and should "
            "be verified from the official docs before designing around it. Current peak "
            "usage is ~{current} req/min; alerting at {alert}% utilization is planned."
        ),
        "unfaithful_template": (
            "{system} API rate limit is {limit} requests per minute. Current peak usage of "
            "{current} req/min is approaching the limit. Alerting at {alert}% utilization."
        ),
        "variants": [
            {"system": s, "limit": l, "current": c, "alert": 80}
            for s in ["OpenAI", "Anthropic", "Cohere", "Together AI", "Replicate"]
            for l in [60, 120, 300, 600]
            for c in [45, 90, 250]
        ],
    },

    {
        "scenario_id": "api_token_expiry_hedged",
        "domain": "api", "qualifier_type": "estimate", "is_ghost": False,
        "conv_template": (
            "User: I believe the access tokens for {system} expire after {hours} hours — "
            "the docs were a bit ambiguous.\n"
            "Assistant: That's a short window for background jobs that run overnight.\n"
            "User: We need silent refresh to avoid mid-job token expiry.\n"
            "Assistant: I'll implement proactive refresh at {refresh_at} minutes before "
            "expiry with a fallback re-auth flow."
        ),
        "faithful_template": (
            "User estimates {system} access tokens expire after {qualifier} {hours} hours — "
            "documentation was unclear, needs verification. Silent refresh will be "
            "implemented at {refresh_at} minutes before expiry."
        ),
        "unfaithful_template": (
            "{system} access tokens expire after {hours} hours. Silent refresh triggers "
            "at {refresh_at} minutes before expiry with a fallback re-authentication flow."
        ),
        "variants": [
            {"system": s, "hours": h, "refresh_at": r}
            for s in ["Salesforce", "HubSpot", "Zendesk", "Intercom", "GitHub"]
            for h in [1, 2, 8, 24]
            for r in [5, 10]
        ],
    },

    {
        "scenario_id": "api_webhook_timeout",
        "domain": "api", "qualifier_type": "approximation", "is_ghost": False,
        "conv_template": (
            "User: I think {system} webhooks have a {timeout}s timeout before they're "
            "considered failed — I've seen it mentioned in passing but haven't confirmed.\n"
            "Assistant: That means our handler must respond within {timeout} seconds.\n"
            "User: Some of our processing takes longer than that.\n"
            "Assistant: We should respond immediately with 200 and process async via a "
            "queue, acknowledging receipt within {ack}ms."
        ),
        "faithful_template": (
            "{system} webhook timeout is {qualifier} {timeout}s — not confirmed from "
            "official docs and should be verified. Handler will respond immediately with "
            "200 and process async to stay within the window."
        ),
        "unfaithful_template": (
            "{system} webhook timeout is {timeout} seconds. The handler acknowledges with "
            "200 immediately and queues processing asynchronously to meet the timeout."
        ),
        "variants": [
            {"system": s, "timeout": t, "ack": 100}
            for s in ["Stripe", "GitHub", "Slack", "Shopify", "Twilio", "PagerDuty"]
            for t in [5, 10, 15, 30]
        ],
    },

    {
        "scenario_id": "api_pagination_limit",
        "domain": "api", "qualifier_type": "vendor_claim", "is_ghost": False,
        "conv_template": (
            "User: The {system} API returns a maximum of {limit} records per page — "
            "at least that's what I recall from the docs.\n"
            "Assistant: So we'd need {pages} pages to fetch {total} records.\n"
            "User: And each page requires a separate request.\n"
            "Assistant: I'll implement cursor-based pagination with {limit}-record pages "
            "and exponential backoff on retries."
        ),
        "faithful_template": (
            "{system} API max page size is {qualifier} {limit} records — recall-based "
            "estimate that should be confirmed in current docs. Cursor-based pagination "
            "will handle batches up to {total} total records."
        ),
        "unfaithful_template": (
            "{system} API returns a maximum of {limit} records per page. Cursor-based "
            "pagination will be used to fetch up to {total} total records efficiently."
        ),
        "variants": [
            {"system": s, "limit": l, "total": t, "pages": t // l}
            for s in ["Salesforce", "HubSpot", "Jira", "Zendesk", "Notion"]
            for l in [100, 250, 500, 1000]
            for t in [5000, 10000, 50000]
        ],
    },

    {
        "scenario_id": "api_batch_size",
        "domain": "api", "qualifier_type": "vendor_claim", "is_ghost": True,
        "conv_template": (
            "User: The {system} batch API supports up to {limit} items per request.\n"
            "Assistant: So we'd need {batches} batches for our {total}-item dataset.\n"
            "User: Each batch takes about {ms}ms to process.\n"
            "Assistant: Total processing time would be {total_time}s. I'll add "
            "parallel batch execution with a {workers}-worker pool."
        ),
        "faithful_template": (
            "{system} batch API limit stated as {limit} items per request — {qualifier} "
            "and needs verification from API docs. For {total} items, "
            "{batches} batches at ~{ms}ms each gives ~{total_time}s total."
        ),
        "unfaithful_template": (
            "{system} batch API supports up to {limit} items per request. Processing "
            "{total} items requires {batches} batches at ~{ms}ms each ({total_time}s total)."
        ),
        "variants": [
            {
                "system": s, "limit": l, "total": t,
                "batches": t // l, "ms": m, "workers": 4,
                "total_time": round((t // l) * m / 1000, 1)
            }
            for s in ["OpenAI", "Cohere", "Pinecone", "Weaviate"]
            for l in [100, 500, 1000]
            for t in [5000, 10000]
            for m in [200, 500]
        ],
    },
]


# ===========================================================================
# DOMAIN: auth
# ===========================================================================

_AUTH_TEMPLATES = [

    {
        "scenario_id": "auth_jwt_expiry_hedged",
        "domain": "auth", "qualifier_type": "estimate", "is_ghost": False,
        "conv_template": (
            "User: I'm not sure, but I think JWT access tokens on {system} expire after "
            "{minutes} minutes — the docs had conflicting examples.\n"
            "Assistant: Short expiry is standard practice for access tokens.\n"
            "User: Mobile apps will need silent refresh to avoid user re-auth.\n"
            "Assistant: I'll implement a refresh window starting at {refresh} minutes "
            "remaining, with fallback to full re-authentication."
        ),
        "faithful_template": (
            "JWT access token expiry on {system} is {qualifier} {minutes} minutes — "
            "conflicting documentation, must be verified before implementation. "
            "Silent refresh triggers at {refresh} minutes remaining."
        ),
        "unfaithful_template": (
            "JWT access tokens on {system} expire after {minutes} minutes. Silent refresh "
            "triggers at {refresh} minutes remaining with full re-auth as fallback."
        ),
        "variants": [
            {"system": s, "minutes": m, "refresh": r}
            for s in ["Auth0", "Okta", "Firebase Auth", "Cognito", "Clerk"]
            for m in [15, 30, 60, 120]
            for r in [2, 5]
        ],
    },

    {
        "scenario_id": "auth_refresh_token_ttl",
        "domain": "auth", "qualifier_type": "vendor_claim", "is_ghost": False,
        "conv_template": (
            "User: I believe {system} refresh tokens last {days} days — I read that "
            "somewhere but I'm not 100% certain.\n"
            "Assistant: {days} days is typical but providers differ.\n"
            "User: Our users expect persistent sessions on mobile.\n"
            "Assistant: I'll store the token issuance timestamp and trigger re-auth "
            "at {warn_days} days with a warning banner."
        ),
        "faithful_template": (
            "{system} refresh token TTL is {qualifier} {days} days — source uncertain, "
            "must be verified from provider docs. Token issuance timestamp will be "
            "stored; re-auth warning fires at {warn_days} days."
        ),
        "unfaithful_template": (
            "{system} refresh tokens expire after {days} days. Issuance timestamps are "
            "stored and re-authentication warnings appear at {warn_days} days."
        ),
        "variants": [
            {"system": s, "days": d, "warn_days": d - 3}
            for s in ["Auth0", "Okta", "Cognito", "Keycloak", "Clerk", "Firebase Auth"]
            for d in [14, 30, 60, 90, 180]
        ],
    },

    {
        "scenario_id": "auth_session_limit",
        "domain": "auth", "qualifier_type": "vendor_claim", "is_ghost": False,
        "conv_template": (
            "User: I think {system} enforces a maximum of {limit} concurrent sessions per "
            "user — might be a plan-specific limit though.\n"
            "Assistant: That would affect users with many devices.\n"
            "User: Enterprise users might log in from desktop, mobile, and two browsers.\n"
            "Assistant: I'll add session management UI so users can revoke old sessions, "
            "and display the current session count."
        ),
        "faithful_template": (
            "{system} concurrent session limit is {qualifier} {limit} per user — "
            "plan-dependent and needs verification. Session management UI "
            "will allow users to revoke old sessions."
        ),
        "unfaithful_template": (
            "{system} enforces a maximum of {limit} concurrent sessions per user. "
            "Session management UI will display active sessions and allow revocation."
        ),
        "variants": [
            {"system": s, "limit": l}
            for s in ["Okta", "Auth0", "Azure AD", "Google Workspace", "OneLogin"]
            for l in [5, 10, 20, 50]
        ],
    },

    {
        "scenario_id": "auth_mfa_window",
        "domain": "auth", "qualifier_type": "approximation", "is_ghost": False,
        "conv_template": (
            "User: I think TOTP codes are valid for {window} seconds on {system} — "
            "that's the standard, but I'm not sure if they use a tighter window.\n"
            "Assistant: Most TOTP implementations allow one past and one future code.\n"
            "User: Clock skew between our servers and users' devices could be an issue.\n"
            "Assistant: I'll accept a ±{skew} second clock skew to handle NTP drift "
            "without widening the window too much."
        ),
        "faithful_template": (
            "TOTP code validity on {system} is {qualifier} {window} seconds — standard "
            "but unverified for this provider. A ±{skew}s clock skew tolerance will be "
            "configured to handle NTP drift."
        ),
        "unfaithful_template": (
            "TOTP codes on {system} are valid for {window} seconds. A ±{skew} second "
            "clock skew tolerance handles NTP drift between servers and user devices."
        ),
        "variants": [
            {"system": s, "window": 30, "skew": sk}
            for s in ["Auth0", "Duo", "Okta", "Google Authenticator", "Azure MFA"]
            for sk in [30, 60, 90]
        ],
    },

    {
        "scenario_id": "auth_oauth_scope_ghost",
        "domain": "auth", "qualifier_type": "vendor_claim", "is_ghost": True,
        "conv_template": (
            "User: The {system} OAuth scope {scope} grants access to {resource}.\n"
            "Assistant: Is that the minimum required scope for our use case?\n"
            "User: We only need read access, so it might be broader than necessary.\n"
            "Assistant: I'll request only {narrow_scope} to follow least-privilege "
            "and avoid unnecessary permissions in the access token."
        ),
        "faithful_template": (
            "{system} OAuth scope {scope} is stated to grant {resource} access — "
            "{qualifier} from official scope documentation, review before shipping. "
            "Narrower scope {narrow_scope} will be requested per least-privilege."
        ),
        "unfaithful_template": (
            "{system} OAuth scope {scope} grants access to {resource}. The narrower "
            "scope {narrow_scope} will be requested to follow least-privilege principles."
        ),
        "variants": [
            {"system": s, "scope": sc, "resource": res, "narrow_scope": ns}
            for s, sc, res, ns in [
                ("GitHub", "repo", "all repositories including private", "repo:read"),
                ("Google", "drive", "full Google Drive access", "drive.readonly"),
                ("Slack", "channels:history", "all channel message history", "channels:read"),
                ("Dropbox", "files.content.write", "full file write access", "files.content.read"),
                ("Spotify", "playlist-modify-public", "all public playlists", "playlist-read-private"),
            ]
        ],
    },
]


# ===========================================================================
# DOMAIN: debug
# ===========================================================================

_DEBUG_TEMPLATES = [

    {
        "scenario_id": "debug_latency_regression",
        "domain": "debug", "qualifier_type": "preliminary", "is_ghost": False,
        "conv_template": (
            "User: I think the latency regression started after deploy {version} — "
            "I'm basing that on eyeballing the dashboard, not a proper analysis.\n"
            "Assistant: We should correlate the deploy timestamp with the p99 spike.\n"
            "User: The spike is roughly {delta}ms added to every request.\n"
            "Assistant: I'll run a git bisect between {prev_version} and {version} "
            "and add tracing to isolate the slow path."
        ),
        "faithful_template": (
            "Latency regression of {qualifier} {delta}ms per request appears to have "
            "started after deploy {version} — based on visual dashboard inspection, "
            "not confirmed with correlation analysis. Bisect between "
            "{prev_version}–{version} planned."
        ),
        "unfaithful_template": (
            "A {delta}ms latency regression was introduced in deploy {version}. "
            "Git bisect between {prev_version} and {version} will identify the root cause."
        ),
        "variants": [
            {"version": v, "prev_version": pv, "delta": d}
            for v, pv in [("v2.3.1", "v2.3.0"), ("v4.1.0", "v4.0.9"),
                          ("v1.8.5", "v1.8.4"), ("v3.0.2", "v3.0.1")]
            for d in [50, 100, 200, 500]
        ],
    },

    {
        "scenario_id": "debug_memory_leak",
        "domain": "debug", "qualifier_type": "preliminary", "is_ghost": False,
        "conv_template": (
            "User: I suspect there's a memory leak in the {service} service — "
            "memory grows at roughly {rate}MB per hour under load, but I haven't "
            "confirmed the root cause yet.\n"
            "Assistant: That's a significant leak if sustained — pod would OOM in "
            "{hours} hours under that growth rate.\n"
            "User: It seems correlated with {trigger}.\n"
            "Assistant: I'll add heap profiling and track allocations during {trigger} "
            "to isolate the leak source."
        ),
        "faithful_template": (
            "{service} service shows {qualifier} {rate}MB/hour memory growth under "
            "load — preliminary observation, root cause unconfirmed. Correlated with "
            "{trigger}; heap profiling will isolate the leak."
        ),
        "unfaithful_template": (
            "{service} service leaks {rate}MB of memory per hour under load, caused by "
            "{trigger}. Heap profiling will confirm and isolate the leak source."
        ),
        "variants": [
            {"service": svc, "rate": r, "hours": round(4096 / r), "trigger": t}
            for svc in ["auth-service", "api-gateway", "worker", "scheduler", "notifier"]
            for r in [5, 20, 50, 100]
            for t in ["large payload processing", "cache invalidation", "bulk imports"]
        ],
    },

    {
        "scenario_id": "debug_error_rate",
        "domain": "debug", "qualifier_type": "approximation", "is_ghost": False,
        "conv_template": (
            "User: The {endpoint} endpoint is failing about {rate}% of the time — "
            "that's a rough estimate from the dashboard, I haven't looked at exact logs.\n"
            "Assistant: {rate}% error rate would be noticeable to users.\n"
            "User: It started happening after we pushed the {feature} feature.\n"
            "Assistant: I'll query the structured logs for the exact failure count "
            "and check error types to narrow down whether it's a {feature} regression."
        ),
        "faithful_template": (
            "{endpoint} endpoint failure rate is {qualifier} {rate}% — dashboard estimate, "
            "exact logs not yet reviewed. Correlates with {feature} feature release; "
            "structured log query will confirm error type distribution."
        ),
        "unfaithful_template": (
            "{endpoint} endpoint fails {rate}% of requests, introduced by the "
            "{feature} feature. Structured log analysis will confirm exact error types."
        ),
        "variants": [
            {"endpoint": ep, "rate": r, "feature": f}
            for ep in ["/api/v1/checkout", "/api/v2/search", "/api/v1/upload",
                       "/api/v1/auth/login", "/api/v2/export"]
            for r in [0.5, 1, 2, 5, 10]
            for f in ["dark launch", "A/B test", "dependency upgrade", "config change"]
        ],
    },

    {
        "scenario_id": "debug_connection_pool",
        "domain": "debug", "qualifier_type": "estimate", "is_ghost": False,
        "conv_template": (
            "User: I believe there's a global connection pool limit of around "
            "{limit} connections to the {db} database — seen it exhausted before "
            "but not sure of the exact cap.\n"
            "Assistant: Pool exhaustion would cause timeouts across all services.\n"
            "User: We're currently using about {current} across all microservices.\n"
            "Assistant: We're close to the limit. I'll add connection count monitoring "
            "and alert at {alert}% utilization."
        ),
        "faithful_template": (
            "{db} connection pool limit is {qualifier} {limit} connections — exact "
            "cap not confirmed. Current usage ~{current} across microservices; "
            "monitoring with {alert}% alert threshold is planned."
        ),
        "unfaithful_template": (
            "{db} global connection pool limit is {limit} connections. Current usage "
            "of {current} connections triggers monitoring with {alert}% alert threshold."
        ),
        "variants": [
            {"db": d, "limit": l, "current": c, "alert": 80}
            for d in ["PostgreSQL", "MySQL", "MongoDB", "Redis", "Elasticsearch"]
            for l, c in [(100, 75), (200, 150), (500, 380), (1000, 750)]
        ],
    },

    {
        "scenario_id": "debug_queue_backlog_ghost",
        "domain": "debug", "qualifier_type": "approximation", "is_ghost": True,
        "conv_template": (
            "User: The {queue} queue has a backlog of {messages} messages.\n"
            "Assistant: At {rate} messages/sec consumer rate, that's {drain}min to clear.\n"
            "User: The backlog has been growing for {hours} hours.\n"
            "Assistant: We need to increase consumer replicas or reduce per-message "
            "processing time to drain faster than production rate."
        ),
        "faithful_template": (
            "{queue} queue backlog is {qualifier} {messages} messages — observed value, "
            "not yet confirmed whether growing or stable. At {rate} msg/s consumer rate, "
            "drain time is ~{drain} minutes; consumer scaling may be needed."
        ),
        "unfaithful_template": (
            "{queue} queue has a backlog of {messages} messages growing over {hours} hours. "
            "At {rate} msg/s consumer rate, drain takes {drain} minutes; "
            "consumer replicas must be increased."
        ),
        "variants": [
            {"queue": q, "messages": m, "rate": r,
             "drain": round(m / r / 60), "hours": h}
            for q in ["payments-queue", "email-queue", "notification-queue",
                      "export-queue", "analytics-queue"]
            for m in [1000, 5000, 10000, 50000]
            for r, h in [(10, 2), (50, 4), (100, 6)]
        ],
    },

    {
        "scenario_id": "debug_deadlock_frequency",
        "domain": "debug", "qualifier_type": "preliminary", "is_ghost": False,
        "conv_template": (
            "User: I'm seeing what looks like a deadlock in the {service} transaction "
            "handler — it happens roughly every {n} transactions in staging, but I "
            "haven't confirmed it's a true deadlock.\n"
            "Assistant: Intermittent deadlocks in transaction handlers usually involve "
            "lock acquisition ordering.\n"
            "User: It always involves the {table_a} and {table_b} tables.\n"
            "Assistant: I'll enforce a consistent lock acquisition order: always lock "
            "{table_a} before {table_b} to prevent the cycle."
        ),
        "faithful_template": (
            "Deadlock {qualifier} every {n} transactions in {service} staging — not yet "
            "confirmed as a true deadlock, observed pattern only. Involves {table_a} and "
            "{table_b} tables; consistent lock ordering is the proposed fix."
        ),
        "unfaithful_template": (
            "Deadlock occurs every {n} transactions in {service} involving {table_a} and "
            "{table_b} tables. Enforcing consistent lock ordering ({table_a} before "
            "{table_b}) will resolve the deadlock."
        ),
        "variants": [
            {"service": svc, "n": n, "table_a": ta, "table_b": tb}
            for svc in ["billing-service", "order-service", "inventory-service"]
            for n in [100, 500, 1000, 5000]
            for ta, tb in [("accounts", "transactions"), ("orders", "inventory"),
                           ("users", "sessions"), ("payments", "refunds")]
        ],
    },
]


# ===========================================================================
# DOMAIN: design
# ===========================================================================

_DESIGN_TEMPLATES = [

    {
        "scenario_id": "design_cache_hit_rate",
        "domain": "design", "qualifier_type": "approximation", "is_ghost": False,
        "conv_template": (
            "User: I'm estimating our {cache} cache hit rate will be around {rate}% — "
            "that's based on a single load test, not production traffic.\n"
            "Assistant: A {rate}% hit rate would reduce origin load significantly.\n"
            "User: If the actual rate is lower, the database could get overwhelmed.\n"
            "Assistant: I'll instrument cache hit/miss metrics from day one and set "
            "an alert if the hit rate drops below {threshold}% in production."
        ),
        "faithful_template": (
            "{cache} cache hit rate projected at {qualifier} {rate}% — based on a single "
            "load test, not representative of production traffic patterns. Alert fires "
            "if production hit rate drops below {threshold}%."
        ),
        "unfaithful_template": (
            "{cache} cache hit rate is {rate}%. Origin load will be reduced significantly. "
            "An alert fires when hit rate drops below {threshold}% in production."
        ),
        "variants": [
            {"cache": c, "rate": r, "threshold": r - 15}
            for c in ["Redis", "Memcached", "CDN", "in-memory LRU", "Varnish"]
            for r in [70, 80, 85, 90, 95]
        ],
    },

    {
        "scenario_id": "design_replica_count",
        "domain": "design", "qualifier_type": "estimate", "is_ghost": False,
        "conv_template": (
            "User: I estimate we'll need {replicas} replicas of the {service} service "
            "for peak load — that's based on last quarter's numbers.\n"
            "Assistant: Traffic patterns change, so that estimate could drift.\n"
            "User: {event} is coming up and volume could be {multiplier}x higher.\n"
            "Assistant: I'd plan for {peak_replicas} peak replicas with auto-scaling "
            "configured to start scaling at {cpu}% CPU."
        ),
        "faithful_template": (
            "{service} replica count is {qualifier} {replicas} for peak load, based on "
            "last quarter's data which may be outdated. {event} could require "
            "{peak_replicas} replicas; auto-scaling triggers at {cpu}% CPU."
        ),
        "unfaithful_template": (
            "{service} service needs {replicas} replicas for peak load. {event} may "
            "require up to {peak_replicas} replicas. Auto-scaling activates at {cpu}% CPU."
        ),
        "variants": [
            {"service": s, "replicas": r, "event": e,
             "multiplier": m, "peak_replicas": r * m, "cpu": 60}
            for s in ["api-gateway", "checkout-service", "search-service", "notification-service"]
            for r in [4, 8, 16, 32]
            for e, m in [("Black Friday", 3), ("product launch", 2), ("quarterly peak", 2)]
        ],
    },

    {
        "scenario_id": "design_throughput_estimate",
        "domain": "design", "qualifier_type": "approximation", "is_ghost": True,
        "conv_template": (
            "User: The {component} can handle {tps} transactions per second.\n"
            "Assistant: That's the baseline — have you stress-tested at {peak_tps} TPS?\n"
            "User: Not yet. The number comes from the vendor benchmarks.\n"
            "Assistant: Vendor benchmarks typically use ideal conditions. I'd add a "
            "{headroom}% capacity buffer and plan a load test before launch."
        ),
        "faithful_template": (
            "{component} capacity is stated as {tps} TPS — {qualifier} from vendor "
            "benchmarks under ideal conditions, not validated under production load. "
            "A {headroom}% buffer is recommended; load test required before launch."
        ),
        "unfaithful_template": (
            "{component} handles {tps} transactions per second per vendor benchmarks. "
            "A {headroom}% capacity buffer is provisioned for peak load."
        ),
        "variants": [
            {"component": c, "tps": t, "peak_tps": t * 2, "headroom": 25}
            for c in ["message queue", "event bus", "API gateway", "load balancer",
                      "database cluster", "streaming pipeline"]
            for t in [1000, 5000, 10000, 50000, 100000]
        ],
    },

    {
        "scenario_id": "design_storage_capacity",
        "domain": "design", "qualifier_type": "estimate", "is_ghost": False,
        "conv_template": (
            "User: Based on preliminary capacity planning, I think we need around "
            "{storage} of {storage_type} storage for the first {period} — "
            "it's based on similar products' growth curves.\n"
            "Assistant: Data growth estimates are notoriously hard to nail early on.\n"
            "User: We could grow faster than expected.\n"
            "Assistant: I'd provision {safety} with dynamic provisioning so we can "
            "scale without downtime if growth outpaces the estimate."
        ),
        "faithful_template": (
            "{storage_type} storage requirement is {qualifier} {storage} for the "
            "first {period} — based on analogous products, not empirical data. "
            "Provisioning {safety} with dynamic scaling as a safety margin."
        ),
        "unfaithful_template": (
            "{storage} of {storage_type} storage is required for the first {period}. "
            "{safety} is provisioned with dynamic scaling enabled to handle higher growth."
        ),
        "variants": [
            {"storage": s, "storage_type": st, "period": p, "safety": sa}
            for s in ["500 GB", "1 TB", "2 TB", "5 TB", "10 TB"]
            for st in ["block", "object", "SSD", "NVMe"]
            for p, sa in [("year", "2×"), ("six months", "1.5×"), ("18 months", "3×")]
        ],
    },

    {
        "scenario_id": "design_sharding_perf",
        "domain": "design", "qualifier_type": "preliminary", "is_ghost": False,
        "conv_template": (
            "User: Preliminary profiling suggests sharding the {table} table on "
            "{shard_key} will give us {factor}x write throughput — "
            "I haven't run it on production data yet.\n"
            "Assistant: Sharding can have non-linear effects depending on key distribution.\n"
            "User: Our write volume is {writes}/sec currently.\n"
            "Assistant: I'd benchmark with production data samples before committing "
            "to the shard key — hot shards could negate the throughput gain."
        ),
        "faithful_template": (
            "Sharding {table} on {shard_key} is {qualifier} projected to give {factor}x "
            "write throughput — based on profiling without production data, not yet "
            "validated. Benchmark with production samples before committing."
        ),
        "unfaithful_template": (
            "Sharding {table} on {shard_key} increases write throughput by {factor}x. "
            "Current write volume of {writes}/sec will scale with the additional shards."
        ),
        "variants": [
            {"table": t, "shard_key": sk, "factor": f, "writes": w}
            for t in ["users", "events", "transactions", "messages", "logs"]
            for sk in ["user_id", "created_at", "tenant_id", "region"]
            for f in [2, 5, 10]
            for w in [1000, 5000, 10000]
        ],
    },

    {
        "scenario_id": "design_cdn_hit_rate",
        "domain": "design", "qualifier_type": "approximation", "is_ghost": False,
        "conv_template": (
            "User: I'm projecting the CDN will serve about {rate}% of read traffic — "
            "that's based on a single load test with simulated data, not real users.\n"
            "Assistant: A {rate}% CDN offload rate would significantly reduce origin load.\n"
            "User: If the actual rate is lower, the origin servers could be overwhelmed.\n"
            "Assistant: I'll instrument CDN hit/miss ratios from day one and add an "
            "origin autoscaling policy as a fallback."
        ),
        "faithful_template": (
            "CDN is projected to serve {qualifier} {rate}% of read traffic — based on "
            "a single test with simulated data, not representative of real user patterns. "
            "Origin autoscaling will provide a fallback if actual offload is lower."
        ),
        "unfaithful_template": (
            "CDN will serve {rate}% of read traffic, reducing origin load substantially. "
            "Origin autoscaling policy is configured as a backup for unexpected load."
        ),
        "variants": [
            {"rate": r, "origin_factor": round(1 - r / 100, 1)}
            for r in [60, 70, 75, 80, 85, 90, 95]
        ],
    },
]


# ===========================================================================
# DOMAIN: compliance
# ===========================================================================

_COMPLIANCE_TEMPLATES = [

    {
        "scenario_id": "compliance_gdpr_deletion",
        "domain": "compliance", "qualifier_type": "unverified_report", "is_ghost": False,
        "conv_template": (
            "User: I read that GDPR Article 17 requires deletion within {days} days — "
            "but I haven't verified this from the regulation text directly.\n"
            "Assistant: GDPR deletion timelines are legally binding and vary by interpretation.\n"
            "User: We need to build our deletion pipeline before our EU launch.\n"
            "Assistant: I'll flag this for legal review and build the pipeline "
            "to a conservative {safe_days}-day target to stay safely under any interpretation."
        ),
        "faithful_template": (
            "GDPR Article 17 deletion deadline is {qualifier} {days} days — from a "
            "secondary source, not verified against the regulation text. Legal review "
            "required; pipeline built to {safe_days}-day conservative target."
        ),
        "unfaithful_template": (
            "GDPR Article 17 requires data deletion within {days} days of request. "
            "The deletion pipeline will be built to a {safe_days}-day execution target."
        ),
        "variants": [
            {"days": 30, "safe_days": s}
            for s in [7, 10, 14, 21]
        ],
    },

    {
        "scenario_id": "compliance_retention_period",
        "domain": "compliance", "qualifier_type": "unverified_report", "is_ghost": False,
        "conv_template": (
            "User: I think {regulation} requires us to retain {data_type} data for "
            "{years} years — I've seen different numbers cited in articles.\n"
            "Assistant: Retention requirements vary by regulation and jurisdiction.\n"
            "User: We need to configure our data lifecycle policies before audit.\n"
            "Assistant: I'll set the retention to {safe_years} years as a conservative "
            "default and flag the exact requirement for legal to confirm."
        ),
        "faithful_template": (
            "{regulation} retention requirement for {data_type} data is {qualifier} "
            "{years} years — conflicting figures from secondary sources, legal review "
            "needed. Conservative {safe_years}-year default will be configured."
        ),
        "unfaithful_template": (
            "{regulation} requires {years}-year retention of {data_type} data. "
            "Data lifecycle policies will be configured to a {safe_years}-year default."
        ),
        "variants": [
            {"regulation": reg, "data_type": dt, "years": y, "safe_years": y + 2}
            for reg in ["SOX", "HIPAA", "PCI-DSS", "CCPA", "GDPR"]
            for dt, y in [("financial", 7), ("medical", 6), ("audit logs", 5),
                          ("transaction", 7), ("user activity", 3)]
        ],
    },

    {
        "scenario_id": "compliance_breach_notification",
        "domain": "compliance", "qualifier_type": "unverified_report", "is_ghost": False,
        "conv_template": (
            "User: I believe {regulation} requires breach notification within "
            "{hours} hours of discovery — I'm basing this on a summary article.\n"
            "Assistant: {hours}-hour notification windows are common but the clock "
            "starts at different points under different regulations.\n"
            "User: We need to build an incident response runbook.\n"
            "Assistant: I'll create a runbook targeting {safe_hours} hours and mark "
            "the exact window for legal review."
        ),
        "faithful_template": (
            "{regulation} breach notification window is {qualifier} {hours} hours — "
            "from an article summary, not from the regulation text itself. Legal review "
            "required; incident runbook targets {safe_hours} hours as a conservative deadline."
        ),
        "unfaithful_template": (
            "{regulation} requires breach notification within {hours} hours of discovery. "
            "The incident response runbook targets {safe_hours} hours to meet the deadline."
        ),
        "variants": [
            {"regulation": reg, "hours": h, "safe_hours": h // 2}
            for reg in ["GDPR", "CCPA", "HIPAA", "NY SHIELD", "PIPEDA"]
            for h in [24, 48, 72]
        ],
    },

    {
        "scenario_id": "compliance_encryption_key_rotation",
        "domain": "compliance", "qualifier_type": "estimate", "is_ghost": False,
        "conv_template": (
            "User: I think {standard} recommends rotating encryption keys every {days} days — "
            "I might be misremembering; I should double-check.\n"
            "Assistant: Key rotation frequency depends on risk profile and the specific standard.\n"
            "User: We're using {algorithm} for at-rest encryption.\n"
            "Assistant: I'll implement automated key rotation at {days} days with "
            "re-encryption of affected data and add the exact requirement to our "
            "compliance checklist."
        ),
        "faithful_template": (
            "{standard} key rotation period is {qualifier} {days} days — user recall "
            "from memory, not verified from standard documentation. {algorithm} "
            "at-rest encryption will rotate at {days} days; exact requirement needs confirmation."
        ),
        "unfaithful_template": (
            "{standard} requires {algorithm} encryption key rotation every {days} days. "
            "Automated key rotation with data re-encryption will be implemented."
        ),
        "variants": [
            {"standard": s, "days": d, "algorithm": a}
            for s in ["NIST SP 800-57", "PCI-DSS", "FedRAMP", "SOC 2"]
            for d in [90, 180, 365]
            for a in ["AES-256", "RSA-4096", "ChaCha20"]
        ],
    },

    {
        "scenario_id": "compliance_phi_access_log",
        "domain": "compliance", "qualifier_type": "unverified_report", "is_ghost": True,
        "conv_template": (
            "User: HIPAA requires PHI access logs to be retained for {years} years.\n"
            "Assistant: That's a significant storage commitment for high-volume systems.\n"
            "User: Our audit log grows at about {growth} GB/year.\n"
            "Assistant: Over {years} years that's {total}GB. I'll implement tiered "
            "storage: hot for recent {hot_years} years, cold archive for the remainder."
        ),
        "faithful_template": (
            "HIPAA PHI access log retention is {qualifier} {years} years — unverified "
            "claim, must be confirmed from HIPAA regulation text before building to "
            "this spec. At {growth} GB/year, tiered storage will be used."
        ),
        "unfaithful_template": (
            "HIPAA requires PHI access logs to be retained for {years} years. "
            "At {growth} GB/year, tiered hot/cold storage handles the {total}GB total."
        ),
        "variants": [
            {"years": y, "growth": g, "total": y * g, "hot_years": 2}
            for y in [6, 7, 10]
            for g in [50, 100, 200, 500]
        ],
    },
]


# ===========================================================================
# DOMAIN: multiagent
# ===========================================================================

_MULTIAGENT_TEMPLATES = [

    {
        "scenario_id": "multiagent_context_budget",
        "domain": "multiagent", "qualifier_type": "estimate", "is_ghost": False,
        "conv_template": (
            "User: My rough estimate is that each sub-agent needs around {tokens} tokens "
            "of context budget — that's just a gut feeling from working with Claude.\n"
            "Assistant: {tokens} tokens per sub-agent is workable but may be tight for "
            "complex reasoning.\n"
            "User: It's really just an estimate — I haven't profiled real sessions.\n"
            "Assistant: I'll make context_budget a configurable parameter defaulting "
            "to {tokens} tokens with per-agent override support."
        ),
        "faithful_template": (
            "Sub-agent context budget is {qualifier} {tokens} tokens per agent — based "
            "on intuition, not empirical profiling. Will be a configurable parameter; "
            "actual budget should be tuned from real session data."
        ),
        "unfaithful_template": (
            "Each sub-agent receives {tokens} tokens of context budget. The parameter "
            "is configurable with per-agent overrides to handle varying task complexity."
        ),
        "variants": [
            {"tokens": t}
            for t in [2000, 4000, 8000, 16000, 32000, 64000]
        ],
    },

    {
        "scenario_id": "multiagent_tool_timeout",
        "domain": "multiagent", "qualifier_type": "approximation", "is_ghost": False,
        "conv_template": (
            "User: I think tool timeout should be around {timeout} seconds for most "
            "agent tools — based on light load testing, not production conditions.\n"
            "Assistant: Some tools will be faster, some slower.\n"
            "User: Long-running tools like file I/O might need more.\n"
            "Assistant: I'll differentiate timeouts by category: fast={fast}s, "
            "standard={timeout}s, long-running={long}s."
        ),
        "faithful_template": (
            "Tool timeout is {qualifier} {timeout}s for standard tools — based on light "
            "load testing, may be insufficient under production load. Per-category "
            "timeouts: fast={fast}s, standard={timeout}s, long-running={long}s."
        ),
        "unfaithful_template": (
            "Tool timeout is {timeout}s for standard agent tools. Per-category "
            "timeouts are configured: fast={fast}s, standard={timeout}s, long-running={long}s."
        ),
        "variants": [
            {"timeout": t, "fast": t // 3, "long": t * 4}
            for t in [10, 15, 30, 60, 120]
        ],
    },

    {
        "scenario_id": "multiagent_parallel_cost",
        "domain": "multiagent", "qualifier_type": "approximation", "is_ghost": True,
        "conv_template": (
            "User: Running {agents} parallel agents will cost approximately "
            "{multiplier}x what a single agent costs.\n"
            "Assistant: That assumes perfectly linear scaling with no coordination overhead.\n"
            "User: Right — shared context and tool calls could add overhead.\n"
            "Assistant: I'll model coordination overhead separately and budget for "
            "a {high_multiplier}x cost multiplier to be safe."
        ),
        "faithful_template": (
            "{agents} parallel agent cost is stated as {qualifier} {multiplier}x single "
            "agent — ignores coordination overhead and shared context costs. "
            "Actual multiplier could be {high_multiplier}x; overhead should be modeled separately."
        ),
        "unfaithful_template": (
            "{agents} parallel agents cost {multiplier}x a single agent. Coordination "
            "overhead is modeled separately with a {high_multiplier}x budget multiplier."
        ),
        "variants": [
            {"agents": a, "multiplier": a, "high_multiplier": round(a * 1.3)}
            for a in [2, 3, 5, 8, 10, 15, 20]
        ],
    },

    {
        "scenario_id": "multiagent_memory_limit",
        "domain": "multiagent", "qualifier_type": "estimate", "is_ghost": False,
        "conv_template": (
            "User: I estimate the orchestrator can handle around {agents} concurrent "
            "sub-agents before hitting memory limits — it's an untested estimate.\n"
            "Assistant: {agents} concurrent agents would each need their own context buffer.\n"
            "User: I haven't stress-tested it under real load.\n"
            "Assistant: I'll make max_concurrent_agents configurable and add memory "
            "monitoring to find the real ceiling empirically."
        ),
        "faithful_template": (
            "Orchestrator concurrent sub-agent capacity is {qualifier} {agents} agents "
            "before memory pressure — untested estimate, not validated under load. "
            "max_concurrent_agents will be configurable for empirical profiling."
        ),
        "unfaithful_template": (
            "Orchestrator supports {agents} concurrent sub-agents within memory limits. "
            "max_concurrent_agents is configurable; empirical profiling will confirm the ceiling."
        ),
        "variants": [
            {"agents": a}
            for a in [5, 10, 15, 20, 25, 30, 50]
        ],
    },

    {
        "scenario_id": "multiagent_schema_version",
        "domain": "multiagent", "qualifier_type": "vendor_claim", "is_ghost": False,
        "conv_template": (
            "User: I think the {framework} multi-agent framework uses schema version "
            "{version} for inter-agent messages — I saw it in an issue comment.\n"
            "Assistant: Schema versions change between releases.\n"
            "User: We need to implement the handoff protocol correctly.\n"
            "Assistant: I'll check the current release notes and implement a schema "
            "version header in all inter-agent messages to handle version negotiation."
        ),
        "faithful_template": (
            "{framework} inter-agent message schema version is {qualifier} {version} — "
            "from an issue comment, not from official release notes. Version header will "
            "be added to all inter-agent messages to handle schema negotiation."
        ),
        "unfaithful_template": (
            "{framework} multi-agent framework uses schema version {version} for "
            "inter-agent messages. Version headers will handle protocol negotiation."
        ),
        "variants": [
            {"framework": f, "version": v}
            for f in ["AutoGen", "CrewAI", "LangGraph", "Semantic Kernel", "CAMEL"]
            for v in ["1.0", "1.1", "2.0", "2.1", "3.0"]
        ],
    },

    {
        "scenario_id": "multiagent_trust_propagation",
        "domain": "multiagent", "qualifier_type": "approximation", "is_ghost": True,
        "conv_template": (
            "User: Trust scores decay by {decay}% per agent hop in our pipeline.\n"
            "Assistant: After {hops} hops the trust would be at {final}%.\n"
            "User: Low-trust results should require human review.\n"
            "Assistant: I'll add a human-in-the-loop gate when trust score "
            "drops below {threshold}% after multi-hop chains."
        ),
        "faithful_template": (
            "Trust score decay rate is {qualifier} {decay}% per agent hop — stated "
            "without empirical validation of the decay model. After {hops} hops trust "
            "reaches ~{final}%; human review gate fires below {threshold}%."
        ),
        "unfaithful_template": (
            "Trust scores decay {decay}% per agent hop. After {hops} hops trust is "
            "{final}%, triggering human review below the {threshold}% gate threshold."
        ),
        "variants": [
            {"decay": d, "hops": h, "final": round(100 * (1 - d/100)**h), "threshold": 40}
            for d in [5, 10, 15, 20]
            for h in [3, 5, 7, 10]
        ],
    },
]


# ===========================================================================
# Assembly
# ===========================================================================

_ALL_TEMPLATES = (
    _API_TEMPLATES
    + _AUTH_TEMPLATES
    + _DEBUG_TEMPLATES
    + _DESIGN_TEMPLATES
    + _COMPLIANCE_TEMPLATES
    + _MULTIAGENT_TEMPLATES
)


def build_parametric_examples(n: int = 5000, seed: int = 42) -> list[dict]:
    """
    Generate up to n DPO training examples by expanding parametric templates.
    Returns a list of dicts matching TripleExample field names.
    Guaranteed 100% verify_triple pass rate.
    Domain-balanced: each domain gets at most ceil(n / n_domains) examples.
    """
    from collections import defaultdict
    import math
    random.seed(seed)

    all_examples: list[dict] = []
    for template in _ALL_TEMPLATES:
        expanded = _expand(template)
        all_examples.extend(expanded)

    print(f"  Parametric expansion: {len(all_examples)} raw examples from "
          f"{len(_ALL_TEMPLATES)} templates")

    # Group by domain
    by_domain: dict[str, list] = defaultdict(list)
    for ex in all_examples:
        by_domain[ex["domain"]].append(ex)

    domains = sorted(by_domain.keys())
    n_domains = len(domains)
    target_per_domain = math.ceil(n / n_domains)

    print(f"  Domains: {domains}, target per domain: {target_per_domain}")

    # Sample each domain up to target_per_domain
    balanced: list[dict] = []
    for d in domains:
        pool = list(by_domain[d])
        random.shuffle(pool)
        take = pool[:target_per_domain]
        # If a domain has fewer examples than target, cycle with different qualifier
        if len(take) < target_per_domain:
            qualifier_pool = _QUAL_EXPLICIT + _GHOST_QUAL
            idx = 0
            while len(take) < target_per_domain:
                base = dict(pool[idx % len(pool)])
                idx += 1
                new_qual = qualifier_pool[idx % len(qualifier_pool)]
                old_faithful = base["faithful_summary"]
                for q in qualifier_pool:
                    if q in old_faithful.lower():
                        replaced = old_faithful.replace(q, new_qual, 1)
                        if new_qual.lower() in replaced.lower():
                            base = dict(base)
                            base["faithful_summary"] = replaced
                            base["id"] = str(uuid.uuid4())
                            take.append(base)
                        break
        balanced.extend(take)

    random.shuffle(balanced)
    result = balanced[:n]

    # Final distribution
    from collections import Counter
    dist = Counter(e["domain"] for e in result)
    print("  Final domain distribution:", dict(sorted(dist.items())))
    return result


if __name__ == "__main__":
    examples = build_parametric_examples(n=5000)
    print(f"Total generated: {len(examples)}")
    # Quick quality check
    from data.build_training_dataset import TripleExample, verify_triple
    sample = [TripleExample(**e) for e in examples[:200]]
    passed = sum(1 for e in sample if verify_triple(e))
    print(f"Quality check (first 200): {passed}/200 pass")
